<Connection>:
    md_bg_color: 0, 0, 0, 1
    size_hint: None, None
    size: 0, 0
    

    FloatLayout:
        ConnectionIcon:
            pos_hint: {"center_x": 0.33, "center_y": 0.33}
            id: first
            card: root

        ConnectionIcon:
            pos_hint: {"center_x": 0.66, "center_y": 0.66}
            id: second
            card: root

<ConnectionIcon>:
    icon_size: pt(38)
    theme_icon_color: "Custom"
    icon_color: root.INACTIVE_COLOR
