<Connection>:
    md_bg_color: 0, 0, 0, 1
    size_hint: None, None
    size: 0, 0
    

    FloatLayout:
        ConnectionIcon:
            pos_hint: {"center_x": 0.33, "center_y": 0.33}
            id: first

        ConnectionIcon:
            pos_hint: {"center_x": 0.66, "center_y": 0.66}
            id: second

<ConnectionIcon>:
    icon_size: dp(80)
    theme_icon_color: "Custom"
    icon_color: 0.6, 0.6, 0.6, 0.6
