<Location>
    md_bg_color: 0, 0, 0, 0
    size_hint: None, None
    size: 200, 200
    

    RelativeLayout:
        Image:
            id: background_image
            source: root.image_sources[3]
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            allow_stretch: True
            keep_ratio: True

        Label:
            id: label
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            text: root.name
